### ISSUE TITLE
拉起登录 提示你没有安装最新版QQ....

### ISSUE THREAD

**Issue by yywanbin** [xyh-fu/QQLoginTest#1]

**Comment by wresource** [comment]
是demo的apk出问题吗？忘记更换apk了，代码那边加了这种情况的解决，部分手机机型可能出现这种情况，在manifest加上query表就好了。

**Comment by yywanbin** [comment]
targetSdk 30
<queries>
        <package android:name="com.tencent.mobileqq" />
        <package android:name="com.tencent.tim" />
        <package android:name="com.tencent.minihd.qq" />
        <package android:name="com.tencent.qqlite" />
    </queries>
