### ISSUE TITLE
请问下，如果要后台做登录机制，app是否只需将access_token和openid传给后台即可？

### ISSUE THREAD

**Issue by yywanbin** [xyh-fu/QQLoginTest#3]

**Comment by yywanbin** [comment]
看Demo工程  好像只是app校验机制，没法和后台同步登录机制，请问有没后台得登录流程？

**Comment by wresource** [comment]
![qrcode_1652753346497.jpg](https://user-images.githubusercontent.com/76175591/168714023-52a997da-ee3d-44b8-be2e-ef6d96d563ce.jpg)
可以加群交流一下
