### ISSUE TITLE
有没有java版本的？

### ISSUE THREAD

**Issue by flow2000** [xyh-fu/QQLoginTest#4]
我原来的代码已经是java了
能不能出个java版本的?

**Comment by wresource** [comment]
这个java版本的代码差不多，如果kotlin转化有问题的话欢迎加群提问![qrcode_1656298890199.jpg](https://user-images.githubusercontent.com/76175591/175852035-eb037cd6-438a-4d55-8b9a-19cb3a0b7dcc.jpg)
